name: Deploy to Azure App Service (Dev)

on:
  push:
    branches: [ dev ]

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0.x'
  RESOURCE_GROUP: 'Snippcheck-Staging'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Setup .NET Core SDK'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Restore dependencies'
      run: dotnet restore SnippInternalIdentity.AuthApi.csproj

    - name: 'Build application'
      run: dotnet build SnippInternalIdentity.AuthApi.csproj --configuration Release --no-restore

    - name: 'Publish application'
      run: dotnet publish SnippInternalIdentity.AuthApi.csproj --configuration Release --no-build --output ./publish

    - name: 'Deploy to Azure App Service'
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME_DEV }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }}
        package: ./publish

    - name: 'Health Check'
      run: |
        sleep 30
        response=$(curl -s -o /dev/null -w "%{http_code}" https://${{ secrets.AZURE_WEBAPP_NAME_DEV }}.azurewebsites.net/api/auth/health || echo "000")
        if [ "$response" = "200" ]; then
          echo "✅ Health check passed - API is running"
        else
          echo "❌ Health check failed - HTTP status: $response"
          exit 1
        fi